### PR TITLE
Allow for authentication token

### PR DESCRIPTION
**Pull request by alexiswl**
Allow client authentication via a token rather than a key

See here for mor infor: https://tools.pieriandx.com/confluence/display/CGWP/API+User+Guide#APIUserGuide-AuthenticationUsingJWTToken

### CODE REVIEW

**Comment by victorskl** [comment]
Ah, ok. Checking this in tick next

**Review by victorskl — APPROVED** [review]
Approve, of course! Didn't aware of you are using this. 

In that case, I don't mind make quick refresh to code base (if any) and, another quickie release. Pls let me know if any other aspect you would like come with next.

Are those in [milestone 0.3.0](https://github.com/umccr/pyriandx/milestone/1), still suits?

Thinking, can do either a patch `0.2.1` or feature release `0.3.0` include those two feature from backlog.

**Comment by victorskl** [comment]
Let me lift GitHub actions check. It might need refresh as well.

**Comment by alexiswl** [comment]
Yeah 0.3.0 is fine! Doesn't look like there's many changes between 0.2.0 and current version on master

**Comment by victorskl** [comment]
Cool, ok. Then, I will work on it.

> current version on master

Yep, I will probably rename/rearrange it into single branch `main` as default branch, too.

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
